### ISSUE TITLE
Enhancement: Create Pane with data on Help Menu

### ISSUE THREAD

**Issue by JerJohn15** [JerJohn15/VocabHunter#4]
**To Do:**
- [ ] The "VocabHunter Website" should either open a web browser to the Vocab Hunter website or display a pane with information to navigate to the website.
- [ ] The "How to "Use Vocab Hunter" option should display a list of instructions for using Vocab Hunter.
- [ ] The "How to Report a Bug" should display instructions on you to report a bug

**Comment by JerJohn15** [comment]
I don't think the  "Vocab Hunter Website" option should remain since the link to the website is detailed in the "About" option.
